// Package source provides the data source adapter registry and provider interface declarations.
// Mirrors the upstream axdata-provider.json declaration pattern from AxData Python.
package source

import (
	"github.com/electkismet/axdata-go/core/schema"
)

// LookupOk retrieves an adapter by name and reports whether it was found.
func LookupOk(name string) (Adapter, bool) {
	a := Lookup(name)
	return a, a != nil
}

// ─── Provider Interface Registry ────────────────────────────────────────

// ProviderInterface declares a source interface and its collector output contract.
// Mirrors axdata-provider.json interfaces + _TDX_LOGICAL_TABLES collector mapping.
type ProviderInterface struct {
	Name        string // interface name, e.g. "stock_codes_tdx"
	SourceCode  string // source code, e.g. "tdx"
	DisplayName string
	Description string

	Table       string // output table name (must exist in schema.TableRegistry)
	Layer       string // output layer, e.g. "core"
	WriteMode   string // write mode from table schema

	// FieldMapping maps adapter output field names → table column names.
	// If nil, direct field name match is used.
	// Format: map[adapter_field_name]table_column_name
	FieldMapping map[string]string
}

// ProviderRegistry holds all declared provider interfaces.
var ProviderRegistry = map[string]*ProviderInterface{
	// ─── TDX (通达信) ───
	"stock_codes_tdx": {
		Name:        "stock_codes_tdx",
		SourceCode:  "tdx",
		DisplayName: "最新股票列表",
		Description: "TDX security code table → stock_basic_exchange",
		Table:       "stock_basic_exchange",
		Layer:       "core",
		WriteMode:   "upsert_by_key",
	},
	"stock_kline_daily_tdx": {
		Name:        "stock_kline_daily_tdx",
		SourceCode:  "tdx",
		DisplayName: "日K线",
		Description: "TDX daily kline → daily table",
		Table:       "daily",
		Layer:       "core",
		WriteMode:   "append",
		FieldMapping: map[string]string{
			"instrument_id": "ts_code",
			"trade_date":    "trade_date",
			"open":          "open",
			"high":          "high",
			"low":           "low",
			"close":         "close",
			"pre_close":     "pre_close",
			"change":        "change",
			"change_pct":    "pct_chg",
			"volume":        "vol",
			"amount":        "amount",
		},
	},
	"stock_suspensions_tdx": {
		Name:        "stock_suspensions_tdx",
		SourceCode:  "tdx",
		DisplayName: "停牌列表",
		Description: "TDX suspension list → stock_suspension",
		Table:       "stock_suspension",
		Layer:       "core",
		WriteMode:   "snapshot",
	},
	"stock_st_list_tdx": {
		Name:        "stock_st_list_tdx",
		SourceCode:  "tdx",
		DisplayName: "ST列表",
		Description: "TDX ST/*ST list → stock_st_list",
		Table:       "stock_st_list",
		Layer:       "core",
		WriteMode:   "snapshot",
	},
	"stock_daily_share_tdx": {
		Name:        "stock_daily_share_tdx",
		SourceCode:  "tdx",
		DisplayName: "每日股本",
		Description: "TDX daily share capital → stock_daily_share",
		Table:       "stock_daily_share",
		Layer:       "core",
		WriteMode:   "append",
	},
	"stock_daily_price_limit_tdx": {
		Name:        "stock_daily_price_limit_tdx",
		SourceCode:  "tdx",
		DisplayName: "每日涨跌停价",
		Description: "TDX daily price limit → stock_price_limit",
		Table:       "stock_price_limit",
		Layer:       "core",
		WriteMode:   "append",
	},
	"stock_limit_ladder_tdx": {
		Name:        "stock_limit_ladder_tdx",
		SourceCode:  "tdx",
		DisplayName: "连板天梯",
		Description: "TDX continuous limit-up ladder → stock_limit_ladder",
		Table:       "stock_limit_ladder",
		Layer:       "core",
		WriteMode:   "snapshot",
	},
	"stock_theme_strength_rank_tdx": {
		Name:        "stock_theme_strength_rank_tdx",
		SourceCode:  "tdx",
		DisplayName: "题材强度排行",
		Description: "TDX theme strength ranking → stock_theme_rank",
		Table:       "stock_theme_rank",
		Layer:       "core",
		WriteMode:   "snapshot",
	},
	// ─── EastMoney (东方财富) ───
	"eastmoney_market_index_realtime": {
		Name:        "eastmoney_market_index_realtime",
		SourceCode:  "eastmoney",
		DisplayName: "指数实时行情",
		Description: "东方财富指数实时行情快照 → market_index_realtime",
		Table:       "market_index_realtime",
		Layer:       "core",
		WriteMode:   "upsert_by_key",
	},
	"eastmoney_market_index_all_em": {
		Name:        "eastmoney_market_index_all_em",
		SourceCode:  "eastmoney",
		DisplayName: "指数全量列表",
		Description: "东方财富指数全量列表 → market_index_all",
		Table:       "market_index_all",
		Layer:       "core",
		WriteMode:   "upsert_by_key",
	},
	"eastmoney_stocks_all_em": {
		Name:        "eastmoney_stocks_all_em",
		SourceCode:  "eastmoney",
		DisplayName: "股票全量列表",
		Description: "东方财富股票全量列表 → stock_basic_exchange",
		Table:       "stock_basic_exchange",
		Layer:       "core",
		WriteMode:   "upsert_by_key",
	},
	"eastmoney_is_trade_day": {
		Name:        "eastmoney_is_trade_day",
		SourceCode:  "eastmoney",
		DisplayName: "当日是否交易日",
		Description: "通过 levizhang.com 查询当日交易状态 → trade_cal",
		Table:       "trade_cal",
		Layer:       "core",
		WriteMode:   "append",
		FieldMapping: map[string]string{
			"is_trade_day": "is_open",
			"trade_date":   "cal_date",
		},
	},
	"eastmoney_trade_days": {
		Name:        "eastmoney_trade_days",
		SourceCode:  "eastmoney",
		DisplayName: "交易日列表",
		Description: "通过 levizhang.com 查询最近交易日列表 → trade_cal",
		Table:       "trade_cal",
		Layer:       "core",
		WriteMode:   "append",
		FieldMapping: map[string]string{
			"trade_date":   "cal_date",
		},
	},
	"eastmoney_stock_realtime_snapshot": {
		Name:        "eastmoney_stock_realtime_snapshot",
		SourceCode:  "eastmoney",
		DisplayName: "个股实时快照",
		Description: "东方财富个股实时快照 → stock_basic_exchange",
		Table:       "stock_basic_exchange",
		Layer:       "core",
		WriteMode:   "upsert_by_key",
		FieldMapping: map[string]string{
			"total_market_value": "total_market",
			"float_market_value": "circ_market",
		},
	},
	"eastmoney_sector_realtime": {
		Name:        "eastmoney_sector_realtime",
		SourceCode:  "eastmoney",
		DisplayName: "板块实时行情",
		Description: "东方财富板块实时行情 → sector_realtime_eastmoney",
		Table:       "sector_realtime_eastmoney",
		Layer:       "core",
		WriteMode:   "upsert_by_key",
	},
	"eastmoney_sector_constituents": {
		Name:        "eastmoney_sector_constituents",
		SourceCode:  "eastmoney",
		DisplayName: "板块成分股",
		Description: "东方财富板块成分股 → sector_constituents_eastmoney",
		Table:       "sector_constituents_eastmoney",
		Layer:       "core",
		WriteMode:   "upsert_by_key",
	},
	"eastmoney_stock_sector_belong": {
		Name:        "eastmoney_stock_sector_belong",
		SourceCode:  "eastmoney",
		DisplayName: "个股板块归属",
		Description: "东方财富个股板块归属 → stock_sector_belong_eastmoney",
		Table:       "stock_sector_belong_eastmoney",
		Layer:       "core",
		WriteMode:   "upsert_by_key",
	},
	"eastmoney_limit_up_pool": {
		Name:        "eastmoney_limit_up_pool",
		SourceCode:  "eastmoney",
		DisplayName: "涨停池",
		Description: "东方财富涨停池 → stock_limit_pool_eastmoney",
		Table:       "stock_limit_pool_eastmoney",
		Layer:       "core",
		WriteMode:   "snapshot",
	},
	"eastmoney_limit_down_pool": {
		Name:        "eastmoney_limit_down_pool",
		SourceCode:  "eastmoney",
		DisplayName: "跌停池",
		Description: "东方财富跌停池 → stock_limit_pool_eastmoney",
		Table:       "stock_limit_pool_eastmoney",
		Layer:       "core",
		WriteMode:   "snapshot",
	},
	"eastmoney_yesterday_limit_up_pool": {
		Name:        "eastmoney_yesterday_limit_up_pool",
		SourceCode:  "eastmoney",
		DisplayName: "昨日涨停池",
		Description: "东方财富昨日涨停池 → stock_limit_pool_eastmoney",
		Table:       "stock_limit_pool_eastmoney",
		Layer:       "core",
		WriteMode:   "snapshot",
	},
	"eastmoney_stock_changes": {
		Name:        "eastmoney_stock_changes",
		SourceCode:  "eastmoney",
		DisplayName: "个股异动概览",
		Description: "东方财富个股异动概览 → stock_realtime_change_eastmoney",
		Table:       "stock_realtime_change_eastmoney",
		Layer:       "core",
		WriteMode:   "append",
	},
	"eastmoney_stock_change_detail": {
		Name:        "eastmoney_stock_change_detail",
		SourceCode:  "eastmoney",
		DisplayName: "个股异动详情",
		Description: "东方财富个股异动详情 → stock_realtime_change_eastmoney",
		Table:       "stock_realtime_change_eastmoney",
		Layer:       "core",
		WriteMode:   "append",
	},
	"eastmoney_dragon_tiger_daily": {
		Name:        "eastmoney_dragon_tiger_daily",
		SourceCode:  "eastmoney",
		DisplayName: "龙虎榜",
		Description: "东方财富龙虎榜 → stock_dragon_tiger_eastmoney",
		Table:       "stock_dragon_tiger_eastmoney",
		Layer:       "core",
		WriteMode:   "append",
	},
	"eastmoney_margin_trading": {
		Name:        "eastmoney_margin_trading",
		SourceCode:  "eastmoney",
		DisplayName: "融资融券",
		Description: "东方财富融资融券 → stock_margin_trading_eastmoney",
		Table:       "stock_margin_trading_eastmoney",
		Layer:       "core",
		WriteMode:   "append",
	},
	"eastmoney_research_reports": {
		Name:        "eastmoney_research_reports",
		SourceCode:  "eastmoney",
		DisplayName: "研报",
		Description: "东方财富研报 → stock_research_reports_eastmoney",
		Table:       "stock_research_reports_eastmoney",
		Layer:       "core",
		WriteMode:   "append",
	},
	// ─── KPH (开盘红) ───
	"kph_market_emotion": {
		Name:        "kph_market_emotion",
		SourceCode:  "kph",
		DisplayName: "市场情绪",
		Description: "开盘红市场情绪指标 → market_sentiment",
		Table:       "market_sentiment",
		Layer:       "core",
		WriteMode:   "upsert_by_key",
		FieldMapping: map[string]string{
			"source":            "source",
			"trade_date":        "trade_date",
			"market_sentiment":  "market_sentiment",
			"market_amount":     "market_amount",
			"rise_count":        "rise_count",
			"fall_count":        "fall_count",
			"flat_count":        "flat_count",
			"limit_up_count":    "limit_up",
			"limit_down_count":  "limit_down",
		},
	},
	"kph_sector_ranking": {
		Name:        "kph_sector_ranking",
		SourceCode:  "kph",
		DisplayName: "板块排行",
		Description: "开盘红板块排行 → sector_rank",
		Table:       "sector_rank",
		Layer:       "core",
		WriteMode:   "upsert_by_key",
		FieldMapping: map[string]string{
			"source":         "source",
			"rank":           "rank",
			"name":           "name",
			"concept_id":     "concept_id",
			"type":           "type",
			"total_amount":   "total_amount",
			"total_volume":   "total_volume",
			"avg_change_pct": "avg_change_pct",
		},
	},
	"kph_sector_plate_detail": {
		Name:        "kph_sector_plate_detail",
		SourceCode:  "kph",
		DisplayName: "板块详情",
		Description: "开盘红板块详情（成分股） → sector_plate_detail",
		Table:       "sector_plate_detail",
		Layer:       "core",
		WriteMode:   "append",
		FieldMapping: map[string]string{
			"source":       "source",
			"concept_id":   "concept_id",
			"concept_name": "concept_name",
			"symbol":       "symbol",
			"name":         "name",
			"change_pct":   "change_pct",
			"trade_date":   "trade_date",
		},
	},
	"kph_sector_concept_detail": {
		Name:        "kph_sector_concept_detail",
		SourceCode:  "kph",
		DisplayName: "概念详情",
		Description: "开盘红概念详情（成分股） → sector_concept_detail",
		Table:       "sector_concept_detail",
		Layer:       "core",
		WriteMode:   "append",
		FieldMapping: map[string]string{
			"source":       "source",
			"concept_id":   "concept_id",
			"concept_name": "concept_name",
			"symbol":       "symbol",
			"name":         "name",
			"change_pct":   "change_pct",
			"trade_date":   "trade_date",
		},
	},
	"kph_sector_constituents_history": {
		Name:        "kph_sector_constituents_history",
		SourceCode:  "kph",
		DisplayName: "成分股历史",
		Description: "开盘红成分股历史 → sector_plate_detail",
		Table:       "sector_plate_detail",
		Layer:       "core",
		WriteMode:   "append",
	},
	"kph_limit_up_history": {
		Name:        "kph_limit_up_history",
		SourceCode:  "kph",
		DisplayName: "涨停历史",
		Description: "开盘红涨停历史 → stock_limit_ladder",
		Table:       "stock_limit_ladder",
		Layer:       "core",
		WriteMode:   "append",
	},
	"kph_limit_down_history": {
		Name:        "kph_limit_down_history",
		SourceCode:  "kph",
		DisplayName: "跌停历史",
		Description: "开盘红跌停历史",
		Table:       "stock_limit_ladder",
		Layer:       "core",
		WriteMode:   "append",
	},
	"kph_wind_vane_history": {
		Name:        "kph_wind_vane_history",
		SourceCode:  "kph",
		DisplayName: "风向标历史",
		Description: "开盘红风向标历史",
		Table:       "stock_limit_ladder",
		Layer:       "core",
		WriteMode:   "append",
	},
	"kph_limit_ladder": {
		Name:        "kph_limit_ladder",
		SourceCode:  "kph",
		DisplayName: "连板天梯",
		Description: "开盘红连板天梯 → stock_limit_ladder",
		Table:       "stock_limit_ladder",
		Layer:       "core",
		WriteMode:   "snapshot",
	},
	"kph_market_review_events": {
		Name:        "kph_market_review_events",
		SourceCode:  "kph",
		DisplayName: "市场复盘",
		Description: "开盘红市场复盘事件",
		Table:       "sector_emotion_detail",
		Layer:       "core",
		WriteMode:   "upsert_by_key",
	},
	"kph_limit_resumption_history": {
		Name:        "kph_limit_resumption_history",
		SourceCode:  "kph",
		DisplayName: "复牌历史",
		Description: "开盘红复牌历史",
		Table:       "stock_suspension",
		Layer:       "core",
		WriteMode:   "append",
	},
	// ─── CLS (财联社) ───
	"cls_market_emotion": {
		Name:        "cls_market_emotion",
		SourceCode:  "cls",
		DisplayName: "财联社市场情绪",
		Description: "财联社市场情绪/热度 → market_sentiment",
		Table:       "market_sentiment",
		Layer:       "core",
		WriteMode:   "upsert_by_key",
		FieldMapping: map[string]string{
			"source":         "source",
			"trade_date":     "trade_date",
			"market_degree":  "market_degree",
			"market_sentiment": "market_sentiment",
			"market_amount":  "market_amount",
		},
	},
	"cls_market_wind": {
		Name:        "cls_market_wind",
		SourceCode:  "cls",
		DisplayName: "财联社市场风向",
		Description: "财联社市场风向 → market_sentiment",
		Table:       "market_sentiment",
		Layer:       "core",
		WriteMode:   "upsert_by_key",
		FieldMapping: map[string]string{
			"source":         "source",
			"trade_date":     "trade_date",
			"market_degree":  "market_degree",
			"market_sentiment": "market_sentiment",
			"market_amount":  "market_amount",
		},
	},
	"cls_sector_top": {
		Name:        "cls_sector_top",
		SourceCode:  "cls",
		DisplayName: "财联社热门板块",
		Description: "财联社热门板块排行 → sector_rank",
		Table:       "sector_rank",
		Layer:       "core",
		WriteMode:   "upsert_by_key",
		FieldMapping: map[string]string{
			"plate_code":    "symbol",
			"plate_name":    "name",
			"change_pct":    "avg_change_pct",
			"main_fund_diff": "total_amount",
			"rise_count":    "rise_count",
			"fall_count":    "fall_count",
		},
	},
	"cls_sector_industry": {
		Name:        "cls_sector_industry",
		SourceCode:  "cls",
		DisplayName: "财联社行业排行",
		Description: "财联社行业排行 → sector_rank",
		Table:       "sector_rank",
		Layer:       "core",
		WriteMode:   "upsert_by_key",
		FieldMapping: map[string]string{
			"plate_code":    "symbol",
			"plate_name":    "name",
			"change_pct":    "avg_change_pct",
			"main_fund_diff": "total_amount",
			"rise_count":    "rise_count",
			"fall_count":    "fall_count",
		},
	},
	"cls_sector_heat": {
		Name:        "cls_sector_heat",
		SourceCode:  "cls",
		DisplayName: "财联社热度排行",
		Description: "财联社热度排行 → sector_rank",
		Table:       "sector_rank",
		Layer:       "core",
		WriteMode:   "upsert_by_key",
		FieldMapping: map[string]string{
			"plate_code": "symbol",
			"plate_name": "name",
			"rank":       "rank",
			"cur_heat":   "cur_heat",
		},
	},
	"cls_sector_hot_concept": {
		Name:        "cls_sector_hot_concept",
		SourceCode:  "cls",
		DisplayName: "财联社热门概念",
		Description: "财联社热门概念排行 → sector_rank",
		Table:       "sector_rank",
		Layer:       "core",
		WriteMode:   "upsert_by_key",
		FieldMapping: map[string]string{
			"plate_code": "symbol",
			"plate_name": "name",
			"rank":       "rank",
			"cur_heat":   "cur_heat",
		},
	},
	"cls_sector_rise_concept": {
		Name:        "cls_sector_rise_concept",
		SourceCode:  "cls",
		DisplayName: "财联社涨幅概念",
		Description: "财联社涨幅概念排行 → sector_rank",
		Table:       "sector_rank",
		Layer:       "core",
		WriteMode:   "upsert_by_key",
		FieldMapping: map[string]string{
			"plate_code":    "symbol",
			"plate_name":    "name",
			"change_pct":    "avg_change_pct",
			"main_fund_diff": "total_amount",
			"rise_count":    "rise_count",
			"fall_count":    "fall_count",
		},
	},
	"cls_sector_volume_concept": {
		Name:        "cls_sector_volume_concept",
		SourceCode:  "cls",
		DisplayName: "财联社成交量概念",
		Description: "财联社成交量概念排行 → sector_rank",
		Table:       "sector_rank",
		Layer:       "core",
		WriteMode:   "upsert_by_key",
	},
	"cls_sector_amount_concept": {
		Name:        "cls_sector_amount_concept",
		SourceCode:  "cls",
		DisplayName: "财联社成交额概念",
		Description: "财联社成交额概念排行 → sector_rank",
		Table:       "sector_rank",
		Layer:       "core",
		WriteMode:   "upsert_by_key",
	},
	"cls_sector_rotation": {
		Name:        "cls_sector_rotation",
		SourceCode:  "cls",
		DisplayName: "财联社板块轮动",
		Description: "财联社板块轮动 → sector_rank",
		Table:       "sector_rank",
		Layer:       "core",
		WriteMode:   "upsert_by_key",
	},
	"cls_sector_popular_stocks": {
		Name:        "cls_sector_popular_stocks",
		SourceCode:  "cls",
		DisplayName: "财联社热门个股",
		Description: "财联社热门个股排行 → stock_rank",
		Table:       "stock_rank",
		Layer:       "core",
		WriteMode:   "upsert_by_key",
		FieldMapping: map[string]string{
			"source":       "source",
			"rank":         "rank",
			"symbol":       "symbol",
			"name":         "name",
			"instrument_id": "instrument_id",
			"last_price":   "last_price",
			"change_pct":   "change_pct",
			"change":       "change",
			"amount":       "amount",
			"volume":       "volume",
		},
	},
	"cls_limit_up_pool": {
		Name:        "cls_limit_up_pool",
		SourceCode:  "cls",
		DisplayName: "财联社涨停池",
		Description: "财联社涨停池 → stock_hot_rank",
		Table:       "stock_hot_rank",
		Layer:       "core",
		WriteMode:   "upsert_by_key",
		FieldMapping: map[string]string{
			"source":       "source",
			"rank":         "rank",
			"symbol":       "symbol",
			"name":         "name",
			"last_price":   "last_price",
			"change_pct":   "change_pct",
			"change":       "change",
		},
	},
	"cls_stock_timeline": {
		Name:        "cls_stock_timeline",
		SourceCode:  "cls",
		DisplayName: "财联社个股时间线",
		Description: "财联社个股时间线",
		Table:       "stock_hot_rank",
		Layer:       "core",
		WriteMode:   "append",
	},
	"cls_news_telegraph": {
		Name:        "cls_news_telegraph",
		SourceCode:  "cls",
		DisplayName: "财联社新闻电报",
		Description: "财联社新闻电报",
		Table:       "sector_emotion_detail",
		Layer:       "core",
		WriteMode:   "append",
	},
	"cls_market_wind_stocks": {
		Name:        "cls_market_wind_stocks",
		SourceCode:  "cls",
		DisplayName: "财联社风口个股",
		Description: "财联社风口个股排行 → stock_basic_exchange",
		Table:       "stock_basic_exchange",
		Layer:       "core",
		WriteMode:   "upsert_by_key",
	},
	"cls_market_mainline": {
		Name:        "cls_market_mainline",
		SourceCode:  "cls",
		DisplayName: "财联社市场主线",
		Description: "财联社市场主线概览 → market_mainline_cls",
		Table:       "market_mainline_cls",
		Layer:       "core",
		WriteMode:   "snapshot",
	},
	"cls_stock_kline": {
		Name:        "cls_stock_kline",
		SourceCode:  "cls",
		DisplayName: "财联社个股K线",
		Description: "财联社个股K线 → daily",
		Table:       "daily",
		Layer:       "core",
		WriteMode:   "append",
	},
	// ─── THS (同花顺) ───
	"stock_hot_rank_ths": {
		Name:        "stock_hot_rank_ths",
		SourceCode:  "ths",
		DisplayName: "同花顺人气榜",
		Description: "同花顺人气榜 → stock_hot_rank",
		Table:       "stock_hot_rank",
		Layer:       "core",
		WriteMode:   "upsert_by_key",
		FieldMapping: map[string]string{
			"source":       "source",
			"rank":         "rank",
			"symbol":       "symbol",
			"name":         "name",
			"instrument_id": "instrument_id",
			"last_price":   "last_price",
			"change_pct":   "change_pct",
			"change":       "change",
			"amount":       "amount",
			"volume":       "volume",
			"tags":         "tags",
		},
	},
	// ─── Wencai (i问财) ───
	"stock_strategy_wencai": {
		Name:        "stock_strategy_wencai",
		SourceCode:  "wencai",
		DisplayName: "i问财选股",
		Description: "i问财自然语言选股 → stock_strategy",
		Table:       "stock_strategy",
		Layer:       "core",
		WriteMode:   "append",
		FieldMapping: map[string]string{
			"strategy_name":    "strategy_name",
			"strategy_type":    "strategy_type",
			"symbol":           "symbol",
			"name":             "name",
			"instrument_id":    "instrument_id",
			"last_price":       "last_price",
			"change_pct":       "change_pct",
			"trade_date":       "trade_date",
		},
	},
	// ─── Tools ───
	"is_trade_day": {
		Name:        "is_trade_day",
		SourceCode:  "eastmoney",
		DisplayName: "判断交易日",
		Description: "工具：判断指定日期是否交易日 → trade_cal",
		Table:       "trade_cal",
		Layer:       "core",
		WriteMode:   "append",
		FieldMapping: map[string]string{
			"is_trade_day": "is_open",
			"trade_date":   "cal_date",
		},
	},
	"get_trade_days": {
		Name:        "get_trade_days",
		SourceCode:  "eastmoney",
		DisplayName: "获取交易日列表",
		Description: "工具：获取最近N个交易日列表 → trade_cal",
		Table:       "trade_cal",
		Layer:       "core",
		WriteMode:   "append",
		FieldMapping: map[string]string{
			"trade_date":   "cal_date",
		},
	},
	// ─── Mock ───
	"daily": {
		Name:        "daily",
		SourceCode:  "mock",
		DisplayName: "模拟日K线",
		Description: "Mock daily OHLCV → daily",
		Table:       "daily",
		Layer:       "core",
		WriteMode:   "append",
	},

	// ─── Tencent (腾讯财经) ───
	"tencent_realtime_snapshot": {
		Name:        "tencent_realtime_snapshot",
		SourceCode:  "tencent",
		DisplayName: "实时行情快照",
		Description: "腾讯实时行情快照 → stock_basic_exchange",
		Table:       "stock_basic_exchange",
		Layer:       "core",
		WriteMode:   "upsert_by_key",
		FieldMapping: map[string]string{
			"instrument_id":        "instrument_id",
			"symbol":               "symbol",
			"exchange":             "exchange",
			"name":                 "name",
			"last_price":           "last_price",
			"pre_close":            "pre_close",
			"open":                 "open",
			"high":                 "high",
			"low":                  "low",
			"change":               "change",
			"change_pct":           "change_pct",
			"volume":               "volume",
			"amount":               "amount",
			"turnover_rate":        "turnover_rate",
			"pe_ttm":               "pe_ttm",
			"pb":                   "pb",
			"total_market_value":   "total_market",
			"float_market_value":   "circ_market",
		},
	},
	"stock_zh_a_spot_tx": {
		Name:        "stock_zh_a_spot_tx",
		SourceCode:  "tencent",
		DisplayName: "个股实时行情",
		Description: "腾讯个股实时行情（按板块排序） → stock_basic_exchange",
		Table:       "stock_basic_exchange",
		Layer:       "core",
		WriteMode:   "upsert_by_key",
	},
	"stock_zh_a_hist_tx": {
		Name:        "stock_zh_a_hist_tx",
		SourceCode:  "tencent",
		DisplayName: "个股日K线",
		Description: "腾讯个股日K线 → daily",
		Table:       "daily",
		Layer:       "core",
		WriteMode:   "append",
		FieldMapping: map[string]string{
			"instrument_id": "ts_code",
			"trade_date":    "trade_date",
			"open":          "open",
			"high":          "high",
			"low":           "low",
			"close":         "close",
			"volume":        "vol",
			"amount":        "amount",
		},
	},
	"stock_zh_index_daily_tx": {
		Name:        "stock_zh_index_daily_tx",
		SourceCode:  "tencent",
		DisplayName: "指数日K线",
		Description: "腾讯指数日K线 → daily",
		Table:       "daily",
		Layer:       "core",
		WriteMode:   "append",
		FieldMapping: map[string]string{
			"instrument_id": "ts_code",
			"trade_date":    "trade_date",
			"open":          "open",
			"high":          "high",
			"low":           "low",
			"close":         "close",
			"volume":        "vol",
			"amount":        "amount",
		},
	},
	"stock_zh_a_tick_tx_js": {
		Name:        "stock_zh_a_tick_tx_js",
		SourceCode:  "tencent",
		DisplayName: "个股逐笔成交",
		Description: "腾讯个股逐笔成交",
		Table:       "stock_basic_exchange",
		Layer:       "core",
		WriteMode:   "append",
	},

	// ─── Sina (新浪财经) ───
	"sina_real_time": {
		Name:        "sina_real_time",
		SourceCode:  "sina",
		DisplayName: "个股实时行情",
		Description: "新浪财经个股实时行情 → stock_basic_exchange",
		Table:       "stock_basic_exchange",
		Layer:       "core",
		WriteMode:   "upsert_by_key",
		FieldMapping: map[string]string{
			"instrument_id": "instrument_id",
			"name":          "name",
			"latest_price":  "last_price",
			"change":        "change",
			"change_pct":    "change_pct",
			"bid":           "bid",
			"ask":           "ask",
			"pre_close":     "pre_close",
			"open":          "open",
			"high":          "high",
			"low":           "low",
			"volume":        "volume",
			"amount":        "amount",
			"tick_time":     "quote_time",
		},
	},
	"sina_kline": {
		Name:        "sina_kline",
		SourceCode:  "sina",
		DisplayName: "个股K线",
		Description: "新浪财经个股K线 → daily",
		Table:       "daily",
		Layer:       "core",
		WriteMode:   "append",
	},
	"sina_rank": {
		Name:        "sina_rank",
		SourceCode:  "sina",
		DisplayName: "市场板块行情",
		Description: "新浪财经市场中心行情数据 → stock_basic_exchange",
		Table:       "stock_basic_exchange",
		Layer:       "core",
		WriteMode:   "upsert_by_key",
	},
	"sina_history": {
		Name:        "sina_history",
		SourceCode:  "sina",
		DisplayName: "个股历史K线",
		Description: "新浪财经个股历史K线 → daily",
		Table:       "daily",
		Layer:       "core",
		WriteMode:   "append",
	},

	// ─── CNINFO (巨潮资讯) ───
	"stock_profile_cninfo": {
		Name:        "stock_profile_cninfo",
		SourceCode:  "cninfo",
		DisplayName: "公司档案",
		Description: "巨潮公司档案信息 → stock_profile_cninfo",
		Table:       "stock_profile_cninfo",
		Layer:       "core",
		WriteMode:   "upsert_by_key",
	},
	"stock_dividend_cninfo": {
		Name:        "stock_dividend_cninfo",
		SourceCode:  "cninfo",
		DisplayName: "分红配送",
		Description: "巨潮分红配送方案 → stock_dividend_cninfo",
		Table:       "stock_dividend_cninfo",
		Layer:       "core",
		WriteMode:   "upsert_by_key",
	},
	"stock_allotment_cninfo": {
		Name:        "stock_allotment_cninfo",
		SourceCode:  "cninfo",
		DisplayName: "股份变动",
		Description: "巨潮股份变动情况 → stock_allotment_cninfo",
		Table:       "stock_allotment_cninfo",
		Layer:       "core",
		WriteMode:   "upsert_by_key",
	},
	"stock_industry_category_cninfo": {
		Name:        "stock_industry_category_cninfo",
		SourceCode:  "cninfo",
		DisplayName: "行业分类",
		Description: "巨潮行业分类 → stock_industry_category_cninfo",
		Table:       "stock_industry_category_cninfo",
		Layer:       "core",
		WriteMode:   "upsert_by_key",
	},
	"stock_ipo_summary_cninfo": {
		Name:        "stock_ipo_summary_cninfo",
		SourceCode:  "cninfo",
		DisplayName: "IPO总览",
		Description: "巨潮IPO上市公司总览 → stock_ipo_summary_cninfo",
		Table:       "stock_ipo_summary_cninfo",
		Layer:       "core",
		WriteMode:   "upsert_by_key",
	},
	"cninfo_announcements": {
		Name:        "cninfo_announcements",
		SourceCode:  "cninfo",
		DisplayName: "公司公告列表",
		Description: "巨潮公司公告列表 → cninfo_announcements",
		Table:       "cninfo_announcements",
		Layer:       "core",
		WriteMode:   "upsert_by_key",
	},
	"cninfo_announcement_detail": {
		Name:        "cninfo_announcement_detail",
		SourceCode:  "cninfo",
		DisplayName: "公司公告详情",
		Description: "巨潮公司公告详情 → cninfo_announcement_detail",
		Table:       "cninfo_announcement_detail",
		Layer:       "core",
		WriteMode:   "append",
	},
	"stock_irm_cninfo": {
		Name:        "stock_irm_cninfo",
		SourceCode:  "cninfo",
		DisplayName: "互动易提问",
		Description: "巨潮互动易投资者提问 → stock_irm_cninfo",
		Table:       "stock_irm_cninfo",
		Layer:       "core",
		WriteMode:   "append",
	},
	"stock_irm_ans_cninfo": {
		Name:        "stock_irm_ans_cninfo",
		SourceCode:  "cninfo",
		DisplayName: "互动易答复",
		Description: "巨潮互动易公司答复 → stock_irm_ans_cninfo",
		Table:       "stock_irm_ans_cninfo",
		Layer:       "core",
		WriteMode:   "append",
	},
	"stock_zh_a_disclosure_report_cninfo": {
		Name:        "stock_zh_a_disclosure_report_cninfo",
		SourceCode:  "cninfo",
		DisplayName: "披露报告",
		Description: "巨潮披露报告全文 → stock_zh_a_disclosure_report_cninfo",
		Table:       "stock_zh_a_disclosure_report_cninfo",
		Layer:       "core",
		WriteMode:   "append",
	},
	"stock_zh_a_disclosure_relation_cninfo": {
		Name:        "stock_zh_a_disclosure_relation_cninfo",
		SourceCode:  "cninfo",
		DisplayName: "关联披露",
		Description: "巨潮关联披露信息 → stock_zh_a_disclosure_relation_cninfo",
		Table:       "stock_zh_a_disclosure_relation_cninfo",
		Layer:       "core",
		WriteMode:   "append",
	},
	"stock_hold_change_cninfo": {
		Name:        "stock_hold_change_cninfo",
		SourceCode:  "cninfo",
		DisplayName: "持股变动",
		Description: "巨潮股东持股变动 → stock_hold_change_cninfo",
		Table:       "stock_hold_change_cninfo",
		Layer:       "core",
		WriteMode:   "append",
	},
	"stock_hold_control_cninfo": {
		Name:        "stock_hold_control_cninfo",
		SourceCode:  "cninfo",
		DisplayName: "控股股东",
		Description: "巨潮控股股东信息 → stock_hold_control_cninfo",
		Table:       "stock_hold_control_cninfo",
		Layer:       "core",
		WriteMode:   "upsert_by_key",
	},
	"stock_hold_num_cninfo": {
		Name:        "stock_hold_num_cninfo",
		SourceCode:  "cninfo",
		DisplayName: "持股数量",
		Description: "巨潮股东持股数量 → stock_hold_num_cninfo",
		Table:       "stock_hold_num_cninfo",
		Layer:       "core",
		WriteMode:   "upsert_by_key",
	},
	"stock_new_gh_cninfo": {
		Name:        "stock_new_gh_cninfo",
		SourceCode:  "cninfo",
		DisplayName: "新股发行",
		Description: "巨潮新股发行信息 → stock_new_gh_cninfo",
		Table:       "stock_new_gh_cninfo",
		Layer:       "core",
		WriteMode:   "upsert_by_key",
	},
	"stock_new_ipo_cninfo": {
		Name:        "stock_new_ipo_cninfo",
		SourceCode:  "cninfo",
		DisplayName: "新股IPO",
		Description: "巨潮新股IPO信息 → stock_new_ipo_cninfo",
		Table:       "stock_new_ipo_cninfo",
		Layer:       "core",
		WriteMode:   "upsert_by_key",
	},
	"stock_share_change_cninfo": {
		Name:        "stock_share_change_cninfo",
		SourceCode:  "cninfo",
		DisplayName: "股本变动",
		Description: "巨潮股本变动情况 → stock_share_change_cninfo",
		Table:       "stock_share_change_cninfo",
		Layer:       "core",
		WriteMode:   "append",
	},
	"fund_report_asset_allocation_cninfo": {
		Name:        "fund_report_asset_allocation_cninfo",
		SourceCode:  "cninfo",
		DisplayName: "基金资产配臵",
		Description: "巨潮基金资产配臵报告 → fund_report_asset_allocation_cninfo",
		Table:       "fund_report_asset_allocation_cninfo",
		Layer:       "core",
		WriteMode:   "append",
	},
	"fund_report_industry_allocation_cninfo": {
		Name:        "fund_report_industry_allocation_cninfo",
		SourceCode:  "cninfo",
		DisplayName: "基金行业配臵",
		Description: "巨潮基金行业配臵报告 → fund_report_industry_allocation_cninfo",
		Table:       "fund_report_industry_allocation_cninfo",
		Layer:       "core",
		WriteMode:   "append",
	},
	"fund_report_stock_cninfo": {
		Name:        "fund_report_stock_cninfo",
		SourceCode:  "cninfo",
		DisplayName: "基金持仓",
		Description: "巨潮基金持仓明细 → fund_report_stock_cninfo",
		Table:       "fund_report_stock_cninfo",
		Layer:       "core",
		WriteMode:   "append",
	},
	"stock_cg_equity_mortgage_cninfo": {
		Name:        "stock_cg_equity_mortgage_cninfo",
		SourceCode:  "cninfo",
		DisplayName: "股权质押",
		Description: "巨潮股权质押信息 → stock_cg_equity_mortgage_cninfo",
		Table:       "stock_cg_equity_mortgage_cninfo",
		Layer:       "core",
		WriteMode:   "append",
	},
	"stock_cg_guarantee_cninfo": {
		Name:        "stock_cg_guarantee_cninfo",
		SourceCode:  "cninfo",
		DisplayName: "公司担保",
		Description: "巨潮公司担保信息 → stock_cg_guarantee_cninfo",
		Table:       "stock_cg_guarantee_cninfo",
		Layer:       "core",
		WriteMode:   "append",
	},
	"stock_cg_lawsuit_cninfo": {
		Name:        "stock_cg_lawsuit_cninfo",
		SourceCode:  "cninfo",
		DisplayName: "公司诉讼",
		Description: "巨潮公司诉讼信息 → stock_cg_lawsuit_cninfo",
		Table:       "stock_cg_lawsuit_cninfo",
		Layer:       "core",
		WriteMode:   "append",
	},
	"stock_hold_management_detail_cninfo": {
		Name:        "stock_hold_management_detail_cninfo",
		SourceCode:  "cninfo",
		DisplayName: "股东管理详情",
		Description: "巨潮股东管理详情 → stock_hold_management_detail_cninfo",
		Table:       "stock_hold_management_detail_cninfo",
		Layer:       "core",
		WriteMode:   "append",
	},
	"stock_industry_change_cninfo": {
		Name:        "stock_industry_change_cninfo",
		SourceCode:  "cninfo",
		DisplayName: "行业变更",
		Description: "巨潮行业变更历史 → stock_industry_change_cninfo",
		Table:       "stock_industry_change_cninfo",
		Layer:       "core",
		WriteMode:   "append",
	},
	"stock_industry_pe_ratio_cninfo": {
		Name:        "stock_industry_pe_ratio_cninfo",
		SourceCode:  "cninfo",
		DisplayName: "行业市盈率",
		Description: "巨潮行业市盈率 → stock_industry_pe_ratio_cninfo",
		Table:       "stock_industry_pe_ratio_cninfo",
		Layer:       "core",
		WriteMode:   "append",
	},
	"stock_rank_forecast_cninfo": {
		Name:        "stock_rank_forecast_cninfo",
		SourceCode:  "cninfo",
		DisplayName: "业绩预告",
		Description: "巨潮业绩预告 → stock_rank_forecast_cninfo",
		Table:       "stock_rank_forecast_cninfo",
		Layer:       "core",
		WriteMode:   "append",
	},
	"bond_corporate_issue_cninfo": {
		Name:        "bond_corporate_issue_cninfo",
		SourceCode:  "cninfo",
		DisplayName: "企业债发行",
		Description: "巨潮企业债发行信息 → bond_corporate_issue_cninfo",
		Table:       "bond_corporate_issue_cninfo",
		Layer:       "core",
		WriteMode:   "append",
	},
	"bond_cov_issue_cninfo": {
		Name:        "bond_cov_issue_cninfo",
		SourceCode:  "cninfo",
		DisplayName: "可转债发行",
		Description: "巨潮可转债发行信息 → bond_cov_issue_cninfo",
		Table:       "bond_cov_issue_cninfo",
		Layer:       "core",
		WriteMode:   "append",
	},
	"bond_cov_stock_issue_cninfo": {
		Name:        "bond_cov_stock_issue_cninfo",
		SourceCode:  "cninfo",
		DisplayName: "转债成分股",
		Description: "巨潮转债成分股信息 → bond_cov_stock_issue_cninfo",
		Table:       "bond_cov_stock_issue_cninfo",
		Layer:       "core",
		WriteMode:   "append",
	},
	"bond_local_government_issue_cninfo": {
		Name:        "bond_local_government_issue_cninfo",
		SourceCode:  "cninfo",
		DisplayName: "地方债发行",
		Description: "巨潮地方政府债发行信息 → bond_local_government_issue_cninfo",
		Table:       "bond_local_government_issue_cninfo",
		Layer:       "core",
		WriteMode:   "append",
	},
	"bond_treasure_issue_cninfo": {
		Name:        "bond_treasure_issue_cninfo",
		SourceCode:  "cninfo",
		DisplayName: "国债发行",
		Description: "巨潮国债发行信息 → bond_treasure_issue_cninfo",
		Table:       "bond_treasure_issue_cninfo",
		Layer:       "core",
		WriteMode:   "append",
	},
}

// GetProviderInterface retrieves a provider declaration by interface name.
func GetProviderInterface(name string) *ProviderInterface {
	return ProviderRegistry[name]
}

// GetOutputTable returns the output table name for an interface.
func GetOutputTable(name string) string {
	if pi := ProviderRegistry[name]; pi != nil {
		return pi.Table
	}
	return ""
}

// GetOutputLayer returns the output layer for an interface.
func GetOutputLayer(name string) string {
	if pi := ProviderRegistry[name]; pi != nil {
		return pi.Layer
	}
	return "core"
}

// InterfaceNames returns all registered provider interface names.
func InterfaceNames() []string {
	names := make([]string, 0, len(ProviderRegistry))
	for name := range ProviderRegistry {
		names = append(names, name)
	}
	return names
}

// InferSchema attempts to derive a TableSchema from a ProviderInterface's FieldMapping.
func (pi *ProviderInterface) InferSchema() *schema.TableSchema {
	if len(pi.FieldMapping) == 0 {
		return nil
	}
	cols := make([]schema.ColumnSchema, 0, len(pi.FieldMapping))
	for _, colName := range pi.FieldMapping {
		cols = append(cols, schema.ColumnSchema{
			Name: colName,
			Type: "string",
		})
	}
	return &schema.TableSchema{
		Name:        pi.Name,
		Columns:     cols,
		Description: pi.Description,
		Layer:       pi.Layer,
		WriteMode:   pi.WriteMode,
	}
}
