package tencent

import (
	"github.com/electkismet/axdata-go/core/plugin"
)

// INTERFACES is the full catalog of Tencent Finance API interfaces.
// This is the single source of truth for interface documentation, examples, and parameters.
var INTERFACES = []plugin.SourceInterface{
	// ─── 实时行情 ────────────────────────────────────────────────────────
	{
		Name:             "stock_quote_tencent",
		DisplayNameZh:    "腾讯实时行情",
		SourceCode:       "tencent",
		AssetClass:       "stock",
		MenuPath:         []string{"腾讯财经", "股票数据", "实时行情"},
		SummaryZh:        "查询A股实时行情，包含最新价、涨跌、买卖五档、成交量、成交额、振幅等完整盘口数据。",
		DescriptionZh:    "通过腾讯财经 qt.gtimg.cn 接口获取股票实时行情。返回字段包括：最新价(close)、开盘价(open)、最高价(high)、最低价(low)、成交量(volume)、成交额(amount)、涨跌额(change)、涨跌幅(change_pct)、前收盘价(pre_close)、买卖五档价格和数量(bid_1~bid_5, ask_1~ask_5)、以及股票名称、代码、上市板块等信息。\n\n该接口返回数据为交易所原始盘口口径，价格单位为元，成交量单位为股，成交额单位为元。涨跌幅单位为百分比(%)，涨跌额为元。\n\n数据频率为实时，交易时段约6秒刷新一次，非交易时段为最近一次收盘价。接口返回 GBK 编码，插件已自动解码。",
		ParamsNoteZh:     "symbols 参数为股票代码列表，支持 AxData 格式（如 600519.SH、000001.SZ）或腾讯格式（如 sh600519、sz000001）。逗号分隔多个代码，最多50只。",
		ParamsExampleZh:  `client.call("stock_quote_tencent", symbols="600519.SH,000001.SZ")`,
		Parameters: []plugin.ParameterDefinition{
			{
				Name:        "symbols",
				Type:        "string",
				Required:    true,
				Description: "股票代码列表，逗号分隔。支持格式：600519.SH / sh600519 / 600519（自动推断沪市）。",
			},
		},
		Fields: []plugin.FieldDefinition{
			{Name: "instrument_id", Type: "string", Description: "AxData 统一股票代码，如 600519.SH"},
			{Name: "code", Type: "string", Description: "腾讯原始代码，如 sh600519"},
			{Name: "name", Type: "string", Description: "股票名称"},
			{Name: "close", Type: "float64", Description: "最新价", Unit: "元"},
			{Name: "open", Type: "float64", Description: "开盘价", Unit: "元"},
			{Name: "high", Type: "float64", Description: "最高价", Unit: "元"},
			{Name: "low", Type: "float64", Description: "最低价", Unit: "元"},
			{Name: "pre_close", Type: "float64", Description: "前收盘价", Unit: "元"},
			{Name: "volume", Type: "int64", Description: "成交量", Unit: "股"},
			{Name: "amount", Type: "float64", Description: "成交额", Unit: "元"},
			{Name: "change", Type: "float64", Description: "涨跌额", Unit: "元"},
			{Name: "change_pct", Type: "float64", Description: "涨跌幅", Unit: "%"},
			{Name: "turnover_rate", Type: "float64", Description: "换手率", Unit: "%"},
			{Name: "bid_1", Type: "float64", Description: "买一价", Unit: "元"},
			{Name: "bid_1_vol", Type: "int64", Description: "买一量", Unit: "股"},
			{Name: "bid_2", Type: "float64", Description: "买二价", Unit: "元"},
			{Name: "bid_2_vol", Type: "int64", Description: "买二量", Unit: "股"},
			{Name: "bid_3", Type: "float64", Description: "买三价", Unit: "元"},
			{Name: "bid_3_vol", Type: "int64", Description: "买三量", Unit: "股"},
			{Name: "bid_4", Type: "float64", Description: "买四价", Unit: "元"},
			{Name: "bid_4_vol", Type: "int64", Description: "买四量", Unit: "股"},
			{Name: "bid_5", Type: "float64", Description: "买五价", Unit: "元"},
			{Name: "bid_5_vol", Type: "int64", Description: "买五量", Unit: "股"},
			{Name: "ask_1", Type: "float64", Description: "卖一价", Unit: "元"},
			{Name: "ask_1_vol", Type: "int64", Description: "卖一量", Unit: "股"},
			{Name: "ask_2", Type: "float64", Description: "卖二价", Unit: "元"},
			{Name: "ask_2_vol", Type: "int64", Description: "卖二量", Unit: "股"},
			{Name: "ask_3", Type: "float64", Description: "卖三价", Unit: "元"},
			{Name: "ask_3_vol", Type: "int64", Description: "卖三量", Unit: "股"},
			{Name: "ask_4", Type: "float64", Description: "卖四价", Unit: "元"},
			{Name: "ask_4_vol", Type: "int64", Description: "卖四量", Unit: "股"},
			{Name: "ask_5", Type: "float64", Description: "卖五价", Unit: "元"},
			{Name: "ask_5_vol", Type: "int64", Description: "卖五量", Unit: "股"},
			{Name: "buy_vol", Type: "int64", Description: "内盘成交量", Unit: "股"},
			{Name: "sell_vol", Type: "int64", Description: "外盘成交量", Unit: "股"},
			{Name: "trade_time", Type: "string", Description: "最近成交时间戳"},
		},
		Example: &plugin.RequestExample{
			Params: map[string]interface{}{"symbols": "600519.SH"},
			Result: []map[string]interface{}{
				{
					"instrument_id": "600519.SH",
					"code":          "sh600519",
					"name":          "贵州茅台",
					"close":         1350.60,
					"open":          1330.03,
					"high":          1361.76,
					"low":           1355.72,
					"pre_close":     1355.72,
					"volume":        55128,
					"amount":        7373462605.00,
					"change":        -5.12,
					"change_pct":    -0.38,
					"turnover_rate": 0.44,
					"bid_1":         1350.60, "bid_1_vol": 1,
					"bid_2":         1350.50, "bid_2_vol": 5,
					"bid_3":         1350.40, "bid_3_vol": 1,
					"bid_4":         1350.35, "bid_4_vol": 1,
					"bid_5":         1350.30, "bid_5_vol": 1,
					"ask_1":         1350.70, "ask_1_vol": 1,
					"ask_2":         1350.88, "ask_2_vol": 11,
					"ask_3":         1350.98, "ask_3_vol": 3,
					"ask_4":         1351.00, "ask_4_vol": 6,
					"ask_5":         1351.10, "ask_5_vol": 1,
					"buy_vol":       27418,
					"sell_vol":      27709,
					"trade_time":    "20260731161450",
				},
			},
		},
	},

	// ─── K线 ───────────────────────────────────────────────────────────────
	{
		Name:             "stock_kline_tencent",
		DisplayNameZh:    "腾讯K线数据",
		SourceCode:       "tencent",
		AssetClass:       "stock",
		MenuPath:         []string{"腾讯财经", "股票数据", "K线数据"},
		SummaryZh:        "查询股票K线数据，支持日/周/月K线，包含前后复权。",
		DescriptionZh:    "通过腾讯财经接口获取股票K线数据，返回日期、开盘、收盘、最高、最低、成交量、成交额等字段。\n\n支持周期：1（分钟）、5（5分钟）、15（15分钟）、30（30分钟）、60（60分钟）、101（日）、201（周）、301（月）。\n\n支持复权：0（不复权）、1（前复权）、2（后复权）。\n\n返回数据为股票交易历史口径，成交量单位为股，成交额单位为元。",
		ParamsNoteZh:     "period 为K线周期，默认101(日K)。adjust 为复权类型，默认1(前复权)。limit 为返回条数，默认500。",
		ParamsExampleZh:  `client.call("stock_kline_tencent", symbols="600519.SH", period="101", limit=10)`,
		Parameters: []plugin.ParameterDefinition{
			{
				Name:        "symbols",
				Type:        "string",
				Required:    true,
				Description: "股票代码，AxData 格式（如 600519.SH）。",
			},
			{
				Name:        "period",
				Type:        "string",
                Required:    false,
                Default:     "101",
                Description: "K线周期：1(分钟)、5(5分钟)、15(15分钟)、30(30分钟)、60(60分钟)、101(日)、201(周)、301(月)。",
			},
			{
				Name:        "adjust",
				Type:        "string",
                Required:    false,
                Default:     "1",
                Description: "复权类型：0(不复权)、1(前复权)、2(后复权)。",
			},
			{
				Name:        "limit",
				Type:        "int",
                Required:    false,
                Default:     "500",
                Description: "返回K线条数，最大1000。",
			},
		},
		Fields: []plugin.FieldDefinition{
			{Name: "instrument_id", Type: "string", Description: "AxData 股票代码"},
			{Name: "trade_date", Type: "string", Description: "交易日期，格式 YYYYMMDD"},
			{Name: "open", Type: "float64", Description: "开盘价", Unit: "元"},
			{Name: "close", Type: "float64", Description: "收盘价", Unit: "元"},
			{Name: "high", Type: "float64", Description: "最高价", Unit: "元"},
			{Name: "low", Type: "float64", Description: "最低价", Unit: "元"},
			{Name: "volume", Type: "int64", Description: "成交量", Unit: "股"},
			{Name: "amount", Type: "float64", Description: "成交额", Unit: "元"},
		},
		Example: &plugin.RequestExample{
			Params: map[string]interface{}{
				"symbols": "600519.SH",
				"period":  "101",
				"limit":   3,
			},
			Result: []map[string]interface{}{
				{
					"instrument_id": "600519.SH",
					"trade_date":    "20260731",
					"open":          1330.03,
					"close":         1350.60,
					"high":          1361.76,
					"low":           1325.77,
					"volume":        5512752,
					"amount":        7373462605.00,
				},
			},
		},
	},

	// ─── 指数行情 ──────────────────────────────────────────────────────────
	{
		Name:             "index_quote_tencent",
		DisplayNameZh:    "腾讯指数行情",
		SourceCode:       "tencent",
		AssetClass:       "index",
		MenuPath:         []string{"腾讯财经", "指数数据", "实时行情"},
		SummaryZh:        "查询上证指数、深证成指、创业板指等指数实时行情。",
		DescriptionZh:    "通过腾讯财经接口获取指数实时行情。返回字段包括指数代码、名称、最新点位、涨跌、涨跌幅、成交量、成交额等。\n\n支持的指数代码：000001（上证指数）、399001（深证成指）、399006（创业板指）、399300（沪深300）等。",
		ParamsNoteZh:     "指数代码可使用 AxData 格式或腾讯格式。",
		ParamsExampleZh:  `client.call("index_quote_tencent", symbols="000001.SH")`,
		Parameters: []plugin.ParameterDefinition{
			{
				Name:        "symbols",
				Type:        "string",
				Required:    true,
				Description: "指数代码列表，逗号分隔。如 000001.SH,399001.SZ。",
			},
		},
		Fields: []plugin.FieldDefinition{
			{Name: "instrument_id", Type: "string", Description: "AxData 指数代码"},
			{Name: "name", Type: "string", Description: "指数名称"},
			{Name: "close", Type: "float64", Description: "最新点位"},
			{Name: "open", Type: "float64", Description: "开盘点位"},
			{Name: "high", Type: "float64", Description: "最高点位"},
			{Name: "low", Type: "float64", Description: "最低点位"},
			{Name: "change", Type: "float64", Description: "涨跌点数"},
			{Name: "change_pct", Type: "float64", Description: "涨跌幅", Unit: "%"},
			{Name: "volume", Type: "int64", Description: "成交量"},
			{Name: "amount", Type: "float64", Description: "成交额", Unit: "元"},
		},
		Example: &plugin.RequestExample{
			Params: map[string]interface{}{"symbols": "000001.SH"},
			Result: []map[string]interface{}{
				{
					"instrument_id": "000001.SH",
					"name":          "上证指数",
					"close":         3833.54,
					"open":          3804.69,
					"high":          3847.09,
					"low":           3822.37,
					"change":        28.85,
					"change_pct":    0.76,
					"volume":        597529427,
					"amount":        1187681546393.00,
				},
			},
		},
	},
}
